version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: everesthood
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  kong:
    image: kong:3.6
    restart: always
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro

  auth:
    image: supabase/gotrue:v2.150.0
    restart: always
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://user:password@postgres:5432/everesthood
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: supersecret
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
    ports:
      - "9999:9999"
    depends_on:
      - postgres

  realtime:
    image: supabase/realtime:v2.25.41
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: everesthood
      DB_USER: user
      DB_PASSWORD: password
      PORT: 4000
      DB_SSL: "false"
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  storage:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - kong
      - auth
      - realtime
      - storage
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/everesthood
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - STORAGE_URL=http://storage:9000
      - AUTH_URL=http://auth:9999
      - KONG_URL=http://kong:8000

  worker:
    build: ./worker
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/everesthood
      - REDIS_URL=redis://redis:6379
    command: ["npm", "run", "start"]

  scheduler:
    build:
      context: ./src/scheduler
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/everesthood
      - REDIS_URL=redis://redis:6379
    command: ["npx", "ts-node", "index.ts"]

volumes:
  pgdata:
  minio_data:
