-- AlterTable
ALTER TABLE "User" ADD COLUMN     "achievements" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "articlesRead" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailyProgress" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "friends" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "lastActiveDate" TIMESTAMP(3),
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "persona" TEXT NOT NULL DEFAULT 'ZenGPT',
ADD COLUMN     "publicProfile" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "sharesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "streak" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "summariesUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "weeklyGoal" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "xp" INTEGER NOT NULL DEFAULT 0;
